# Generated by Django 4.1 on 2022-08-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('img', models.ImageField(upload_to='media_imgs')),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('larg', 'Larg')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='flavor',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('blue', 'Blue')], default='red', max_length=100),
        ),
    ]
